---
# This workflow integrates qwiet.ai preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Download ShiftLeft CLI
    #   run: |
    #     tar -xvf sl-latest-linux-x64.tar.gz && chmod a+rx sl

    # - name: Print GitHub Environment Variables
    #   shell: bash
    #   run: |
    #     echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
    #     echo "GITHUB_SHA: $GITHUB_SHA"
    #     echo "GITHUB_REF: $GITHUB_REF"
    #     echo "GITHUB_ACTOR: $GITHUB_ACTOR"

    # - name: Setup Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '20'

    # - name: Install Node.js dependencies
    #   run: npm install

    # - name: preZero Static Analysis
    #   run: |
    #     ./sl analyze --verbose --strict --wait
    #   env:
    #     SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    #     SHIFTLEFT_API_HOST: www.shiftleft.io
    #     SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
    #     SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

    # - name: Export Sarif Report qwiet ai
    #   shell: bash
    #   run: |
    #     ./sl sarif export --app shiftleft-js-demo
    #   env:
    #     SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: formatted4.sarif
        category: qwiet-prezero
    # - name: Upload SARIF via GitHub REST API
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     REPO: ${{ github.repository }}
    #     COMMIT_SHA: ${{ github.sha }}
    #     BRANCH: ${{ github.ref }}
    #   run: |
    #     SARIF_FILE="formatted4.sarif"
    #     BASE64_SARIF=$(gzip -c "$SARIF_FILE" | base64 -w0)
    #     PAYLOAD=$(jq -n \
    #     --arg commit_sha "$COMMIT_SHA" \
    #     --arg ref "$BRANCH" \
    #     --arg sarif "$BASE64_SARIF" \
    #     '{commit_sha: $commit_sha, ref: $ref, sarif: $sarif}')
    #     curl -X POST \
    #       -H "Authorization: token $GITHUB_TOKEN" \
    #       -H "Accept: application/vnd.github+json" \
    #       https://api.github.com/repos/$REPO/code-scanning/sarifs \
    #       -d "$PAYLOAD"

    - name: Upload report file
      uses: actions/upload-artifact@v4
      with:
        name: sarif-report
        path: formatted4.sarif
